<?php
/**
 * @file
 * bhutan_spash_page.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function bhutan_spash_page_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'field_collection_item-field_collection_teaser-field_description'
  $field_instances['field_collection_item-field_collection_teaser-field_description'] = array(
    'bundle' => 'field_collection_teaser',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter the description text for this resource collection',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_description',
    'label' => 'Description',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'field_collection_item-field_collection_teaser-field_featured_resources'
  $field_instances['field_collection_item-field_collection_teaser-field_featured_resources'] = array(
    'bundle' => 'field_collection_teaser',
    'default_value' => array(
      0 => array(
        'title' => 'This is a useful resource',
        'url' => 'home#',
      ),
    ),
    'deleted' => 0,
    'description' => 'Enter a series of links to featured resources within this collection',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'link',
        'settings' => array(),
        'type' => 'link_default',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_featured_resources',
    'label' => 'Featured Resources',
    'required' => 1,
    'settings' => array(
      'absolute_url' => 0,
      'attributes' => array(
        'class' => '',
        'configurable_class' => 0,
        'configurable_title' => 0,
        'rel' => '',
        'target' => 'default',
        'title' => '',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'rel_remove' => 'default',
      'title' => 'required',
      'title_label_use_field_label' => 0,
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 'optional',
      'user_register_form' => FALSE,
      'validate_url' => 1,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'link',
      'settings' => array(),
      'type' => 'link_field',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'field_collection_item-field_collection_teaser-field_icon_class'
  $field_instances['field_collection_item-field_collection_teaser-field_icon_class'] = array(
    'bundle' => 'field_collection_teaser',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'The class of the icon in Shanticon list to use for this resource collection',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_icon_class',
    'label' => 'Icon Class',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'field_collection_item-field_collection_teaser-field_title'
  $field_instances['field_collection_item-field_collection_teaser-field_title'] = array(
    'bundle' => 'field_collection_teaser',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter the title for this resource collection',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_title',
    'label' => 'Title',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 0,
    ),
  );

  // Exported field_instance: 'field_collection_item-field_collection_teaser-field_url'
  $field_instances['field_collection_item-field_collection_teaser-field_url'] = array(
    'bundle' => 'field_collection_teaser',
    'default_value' => array(
      0 => array(
        'value' => 'home',
      ),
    ),
    'deleted' => 0,
    'description' => 'The local page url that displays this resource',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_url',
    'label' => 'URL',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-splash_page-field_collection_teaser'
  $field_instances['node-splash_page-field_collection_teaser'] = array(
    'bundle' => 'splash_page',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'field_collection',
        'settings' => array(
          'add' => 'Add',
          'delete' => 'Delete',
          'description' => TRUE,
          'edit' => 'Edit',
          'view_mode' => 'full',
        ),
        'type' => 'field_collection_view',
        'weight' => 0,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'field_collection',
        'settings' => array(
          'add' => '',
          'delete' => '',
          'description' => 0,
          'edit' => '',
          'view_mode' => 'full',
        ),
        'type' => 'field_collection_view',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_collection_teaser',
    'label' => 'Collection Teaser',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'field_collection',
      'settings' => array(),
      'type' => 'field_collection_embed',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-splash_page-field_grid_inset'
  $field_instances['node-splash_page-field_grid_inset'] = array(
    'bundle' => 'splash_page',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
      'full' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_grid_inset',
    'label' => 'Grid Inset',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-splash_page-field_overview'
  $field_instances['node-splash_page-field_overview'] = array(
    'bundle' => 'splash_page',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Overview text is in the box below the photo grid',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'full' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_overview',
    'label' => 'Overview Text',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Collection Teaser');
  t('Description');
  t('Enter a series of links to featured resources within this collection');
  t('Enter the description text for this resource collection');
  t('Enter the title for this resource collection');
  t('Featured Resources');
  t('Grid Inset');
  t('Icon Class');
  t('Overview Text');
  t('Overview text is in the box below the photo grid');
  t('The class of the icon in Shanticon list to use for this resource collection');
  t('The local page url that displays this resource');
  t('Title');
  t('URL');

  return $field_instances;
}
